---
- hosts: webservers
  vars:
  - warName: java-example.war
  - warRemotePath: /opt/apache-tomcat-9.0.95/webapps/

  tasks:
  - name: Copy WAR to Remote server
    copy: src=target/{{ warName }} dest={{ warRemotePath }}/{{ warName }} owner=tomcat group=tomcat
   
